# Generated by Django 4.0.5 on 2022-06-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_persona_donador_alter_persona_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='donador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
